export const blogs = [
  {
    slug: "customer-gave-1-star-how-to-reply",
    title: "Customer Gave 1-Star? How to Reply So It Turns Into 5-Star",
    description: "Learn how to respond to negative reviews like a pro. Real examples from Indian businesses that turn angry customers into loyal advocates.",
    category: "Reviews / Business",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "90-percent-businesses-mistake-negative-reviews",
    title: "90% Businesses Make This Mistake Replying to Negative Reviews",
    description: "Discover the common mistake Indian businesses make when handling negative feedback and how to avoid it.",
    category: "Reviews / Business",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "15-google-review-reply-templates",
    title: "15 Ready-to-Use Google Review Reply Templates (Copy & Paste)",
    description: "Copy and paste these professional review reply templates for your business. Save time and respond like a pro.",
    category: "Reviews / Business",
    date: "2026-05-05",
    featured: false,
  },
  {
    slug: "should-you-reply-to-every-review",
    title: "Should You Reply to Every Review? Truth for Indian Businesses",
    description: "The honest truth about responding to customer reviews. When to reply, when to skip, and what works best in India.",
    category: "Reviews / Business",
    date: "2026-05-05",
    featured: false,
  },
  {
    slug: "from-0-to-100k-reach-captions",
    title: "From 0 to 100K Reach: How Captions Alone Can Grow Your Instagram",
    description: "Real strategies Indian creators used to grow from zero to viral reach using only powerful captions.",
    category: "Content / Social Media",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "instagram-captions-save-share",
    title: "Instagram Captions That Make People Save & Share (Proven Tricks)",
    description: "Learn the caption writing secrets that make your posts go viral on Instagram. Real examples from successful Indian creators.",
    category: "Content / Social Media",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "why-reels-not-going-viral-hook-formulas",
    title: "Why Your Reels Aren't Going Viral (7 Proven Hook Formulas)",
    description: "Stop guessing. Use these 7 hook formulas that actually work for Indian Instagram creators in 2026.",
    category: "Content / Social Media",
    date: "2026-05-05",
    featured: false,
  },
  {
    slug: "turn-1-content-into-10-posts",
    title: "Turn 1 Piece of Content Into 10 Posts (Step-by-Step Guide)",
    description: "Repurpose your content like a pro. Complete guide for Indian creators and small businesses.",
    category: "Content / Social Media",
    date: "2026-05-05",
    featured: false,
  },
  {
    slug: "free-ai-tools-that-actually-work",
    title: "Free AI Tools That Actually Work in India (No Useless List)",
    description: "Only the best free AI tools that work in India. No fluff, no paid tools disguised as free.",
    category: "AI + Practical",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "stop-using-ai-like-this-mistakes",
    title: "Stop Using AI Like This – Biggest Mistakes Beginners Make",
    description: "Common AI mistakes Indians make and how to fix them. Practical tips for beginners.",
    category: "AI + Practical",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "does-ai-content-rank-google-india-2026",
    title: "Does AI Content Rank on Google in India? (2026 Reality)",
    description: "The real answer about AI content and Google rankings in 2026. No myths, just facts.",
    category: "AI + Practical",
    date: "2026-05-05",
    featured: false,
  },
  {
    slug: "how-indians-using-ai-wrong-fixing-it",
    title: "How Indians Are Using AI Wrong (And Fixing It)",
    description: "Common AI usage mistakes in India and practical solutions. Real examples from students and professionals.",
    category: "AI + Practical",
    date: "2026-05-05",
    featured: false,
  },
  {
    slug: "hidden-free-tools-website-owner",
    title: "Hidden Free Tools Every Website Owner Should Know",
    description: "Essential free tools for website owners in India. Boost your site performance without spending money.",
    category: "Tools / SEO / Earning",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "earn-from-low-traffic-websites-india",
    title: "How to Earn from Low Traffic Websites in India",
    description: "Proven strategies to monetize websites with low traffic. Real Indian case studies and practical tips.",
    category: "Tools / SEO / Earning",
    date: "2026-05-05",
    featured: true,
  },
  {
    slug: "adsense-rejected-fix-5-issues",
    title: "AdSense Rejected? Fix These 5 Things and Get Approval",
    description: "Google AdSense approval guide for Indian websites. Fix these 5 common issues and get approved faster.",
    category: "Tools / SEO / Earning",
    date: "2026-05-05",
    featured: false,
  },
];
